### ISSUE TITLE
Maps - Revisar comparibilidad con API 18

### ISSUE THREAD

**Issue by PaoloVC** [PaoloVC/TakeUrPills#6]
Se debe asegurar que la solución de Google Maps sea compatible con el API 18 a como son los requerimientos del proyecto

**Comment by brymurod** [comment]
compile 'com.google.android.gms:play-services-maps:9.0.2'
compile 'com.google.android.gms:play-services-location:9.0.2'

Con esos se cumple eso del API 18, estan en el Build.Gradle
